export const actionType = {
  // USER
  LOG_USER: "LOG_USER",
  CREATE_USER: "CREATE_USER",
  SAVE_USERNAME: "SAVE_USERNAME",
  SAVE_USERPIC: "SAVE_USERPIC",
  DELETE_USER: "DELETE_USER",
  // POSTS
  GET_POSTS: "GET_POSTS",
};
