export const actionType = {
  ////////////////
  //  USER
  ////////////////

  // Login
  LOG_USER: "LOG_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  // Signup
  CREATE_USER: "CREATE_USER",
  USER_CREATED: "USER_CREATED",
  USER_FAIL: "USER_FAIL",
  // Username
  ADD_USERNAME: "ADD_USERNAME",
  EDIT_USERNAME: "EDIT_USERNAME",
  USERNAME_ADDED: "USERNAME_ADDED",
  USERNAME_EDITED: "USERNAME_EDITED",
  USERNAME_FAIL: "USERNAME_FAIL",
  // Userpic
  SAVE_USERPIC: "SAVE_USERPIC",
  // Verbs
  GET_USERS: "GET_USERS",
  GET_MODS: "GET_MODS",
  DELETE_USER: "DELETE_USER",
  // Like
  LIKE_POST: "LIKE_POST",
  //Follow:
  UPDATE_FOLLOW: "UPDATE_FOLLOW",
  // Profile
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_FOLLOWERS: "GET_FOLLOWERS",
  CLEAN_PROFILE_VISIT: "CLEAN_PROFILE_VISIT",
  CLEAN_PROFILE_POSTS: "CLEAN_PROFILE_POSTS",
  // UI
  TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
  TOGGLE_VISITOR: "TOGGLE_VISITOR",
  SET_LANGUAGE: "SET_LANGUAGE",
  // Errors
  SET_ERROR_USER: "SET_ERROR_USER",
  CLEAR_ERROR_USER: "CLEAR_ERROR_USER",

  ////////////////
  //  POSTS
  ////////////////

  // Verbs
  GET_POSTS: "GET_POSTS",
  GET_POST_BY_ID: "GET_POST_BY_ID",
  GET_COMMENTS: "GET_COMMENTS",
  GET_LIKES: "GET_LIKES",
  GET_USER_POSTS: "GET_USER_POSTS",
  GET_REPLIES: "GET_REPLIES",
  DELETE_POST: "DELETE_POST",
  // Img-preview
  SAVE_POST_PIC: "SAVE_POST_PIC",
  SET_PREVIEW_LOADER: "SET_PREVIEW_LOADER",
  GET_PREVIEW_DATA: "GET_PREVIEW_DATA",
  SET_PREVIEW_DATA: "SET_PREVIEW_DATA",
  SAVE_GIF_URL: "SAVE_GIF_URL",
  CLEAR_TEMP_POST_PIC: "CLEAR_TEMP_POST_PIC",
  CLEAR_TEMP_PREVIEW: "CLEAR_TEMP_PREVIEW",
  CLEAR_PREVIEW_IMG: "CLEAR_PREVIEW_IMG",
  // Create
  CREATE_POST: "CREATE_POST",
  CREATE_COMMENT: "CREATE_COMMENT",
  CREATE_REPLY: "CREATE_REPLY",
  EDIT_POST: "EDIT_POST",
  SET_EDIT_ID: "SET_EDIT_ID",
  // UI
  TO_COMMENT: "TO_COMMENT",
  CLEAR_LAST_ADDED: "CLEAR_LAST_ADDED",
  TOGGLE_EDIT_MODAL: "TOGGLE_EDIT_MODAL",
  SET_ERROR_POST: "SET_ERROR_POST",
  RESET_REPLIES: "RESET_REPLIES",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  GET_SEARCH_RESULTS: " GET_SEARCH_RESULTS",
  // Errors
  CLEAR_ERROR_POST: "CLEAR_ERROR_POST",
  SESSION_EXPIRED: "SESSION_EXPIRED",
};
