export const actionType = {
  // USER
  LOG_USER: "LOG_USER",
  CREATE_USER: "CREATE_USER",
  SAVE_USERNAME: "SAVE_USERNAME",
  SAVE_USERPIC: "SAVE_USERPIC",
  DELETE_USER: "DELETE_USER",
  // USER__ERRORS
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  // POSTS
  GET_POSTS: "GET_POSTS",
};
